gui:
  theme:
    activeBorderColor:
      - '#4bad87'
      - bold
    inactiveBorderColor:
      - '#bcd1dd'
    searchingActiveBorderColor:
      - cyan
      - bold
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - blue # set to `default` to have no background colour
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - '#fe7669'
    defaultFgColor:
      - default
    nerdFontsVersion: "3"
    border: 'double'
